### ISSUE TITLE
Validate deploy artifact git checkout

### ISSUE THREAD

**Issue by zendoodles** [palantirnet/the-build#36]
If something goes wrong in the acquia checkout, all the git commands are performed on the main project github checkout which is un-good. Instead, we should validate the git checkout and fail gracefully if it didn't go as planned. 

Possibly related or solved similarly to https://github.com/palantirnet/the-build/issues/32

**Comment by becw** [comment]
Artifact builds are refactored in 2.0, but we should validate that failing to check out the repo will fail the whole build.

**Comment by becw** [comment]
Related to #32.

**Comment by byrond** [comment]
I verified this by renaming the directory where the remote was installed to make it unavailable.  `phing artifact` then resulted in:
```
example > artifact-safeToBuild:

     [echo] Deploy environment:   other
     [echo] Repository status:    clean
     [echo] Artifact repository:  artifacts/build
     [echo]                       origin=/home/vagrant/remote
     [echo] Destination branch:   artifact-master
     [echo] Ok, ready to build!

example > artifact-initializeRepository:

     [exec] HEAD is now at 76a3760d initial commit

example > artifact-setupBranch:

     [echo] Remote branch does not exist. Creating 'artifact-master' on remote repository...
[phingcall] /var/www/example.local/vendor/palantirnet/the-build/tasks/artifact.xml:170:12: /var/www/example.local/vendor/palantirnet/the-build/tasks/artifact.xml:175:20: /var/www/example.local/vendor/palantirnet/the-build/tasks/artifact.xml:177:142: 
Failed to create remote branch: base branch 'master' could not be fetched.
    [phing] /var/www/example.local/vendor/palantirnet/the-build/tasks/artifact.xml:58:50: 
Execution of the target buildfile failed. Aborting.
```

This also fails (less gracefully) if the remote cannot be reached and `artifacts/build` doesn't yet exist:
```
example > artifact-safeToBuild:

     [echo] Deploy environment:   other
     [echo] Repository status:    clean
     [echo] Artifact repository:  does not exist (will be created)
     [echo] Destination branch:   artifact-master
     [echo] Ok, ready to build!

example > artifact-initializeRepository:

     [echo] Cloning the repository from /home/vagrant/remote
[phingcall] /var/www/example.local/vendor/palantirnet/the-build/tasks/artifact.xml:152:12: /var/www/example.local/vendor/palantirnet/the-build/tasks/artifact.xml:156:98: 
The remote end hung up unexpectedly
#0 /var/www/example.local/vendor/phing/phing/classes/phing/UnknownElement.php(100): GitCloneTask->main()
#1 /var/www/example.local/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#2 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/SequentialTask.php(58): Task->perform()
#3 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/IfTask.php(172): SequentialTask->main()
#4 /var/www/example.local/vendor/phing/phing/classes/phing/TaskAdapter.php(61): IfTask->main(Object(Project))
#5 /var/www/example.local/vendor/phing/phing/classes/phing/UnknownElement.php(100): TaskAdapter->main()
#6 /var/www/example.local/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#7 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#8 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#9 /var/www/example.local/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#10 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/PhingTask.php(285): Project->executeTarget('artifact-initia...')
#11 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/PhingTask.php(155): PhingTask->processFile()
#12 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/PhingCallTask.php(172): PhingTask->main()
#13 /var/www/example.local/vendor/phing/phing/classes/phing/UnknownElement.php(100): PhingCallTask->main()
#14 /var/www/example.local/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#15 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#16 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#17 /var/www/example.local/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#18 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/PhingTask.php(285): Project->executeTarget('artifact-main')
#19 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/PhingTask.php(155): PhingTask->processFile()
#20 /var/www/example.local/vendor/phing/phing/classes/phing/UnknownElement.php(100): PhingTask->main()
#21 /var/www/example.local/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#22 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#23 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#24 /var/www/example.local/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#25 /var/www/example.local/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('artifact')
#26 /var/www/example.local/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)
#27 /var/www/example.local/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
#28 /var/www/example.local/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#29 /var/www/example.local/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#30 /var/www/example.local/vendor/phing/phing/bin/phing(14): require_once('/var/www/exampl...')
#31 {main}

Previous VersionControl_Git_Exception: Some errors in executing git command

Output:

Error:
fatal: repository '/home/vagrant/remote' does not exist
 in /var/www/example.local/vendor/phing/phing/classes/phing/tasks/ext/git/GitCloneTask.php on line 137
#0 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/ext/git/GitCloneTask.php(137): VersionControl_Git_Util_Command->execute()
#1 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/ext/git/GitCloneTask.php(90): GitCloneTask->doClone(Object(VersionControl_Git))
#2 /var/www/example.local/vendor/phing/phing/classes/phing/UnknownElement.php(100): GitCloneTask->main()
#3 /var/www/example.local/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#4 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/SequentialTask.php(58): Task->perform()
#5 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/IfTask.php(172): SequentialTask->main()
#6 /var/www/example.local/vendor/phing/phing/classes/phing/TaskAdapter.php(61): IfTask->main(Object(Project))
#7 /var/www/example.local/vendor/phing/phing/classes/phing/UnknownElement.php(100): TaskAdapter->main()
#8 /var/www/example.local/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#9 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#10 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#11 /var/www/example.local/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#12 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/PhingTask.php(285): Project->executeTarget('artifact-initia...')
#13 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/PhingTask.php(155): PhingTask->processFile()
#14 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/PhingCallTask.php(172): PhingTask->main()
#15 /var/www/example.local/vendor/phing/phing/classes/phing/UnknownElement.php(100): PhingCallTask->main()
#16 /var/www/example.local/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#17 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#18 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#19 /var/www/example.local/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#20 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/PhingTask.php(285): Project->executeTarget('artifact-main')
#21 /var/www/example.local/vendor/phing/phing/classes/phing/tasks/system/PhingTask.php(155): PhingTask->processFile()
#22 /var/www/example.local/vendor/phing/phing/classes/phing/UnknownElement.php(100): PhingTask->main()
#23 /var/www/example.local/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#24 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#25 /var/www/example.local/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#26 /var/www/example.local/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#27 /var/www/example.local/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('artifact')
#28 /var/www/example.local/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)
#29 /var/www/example.local/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
#30 /var/www/example.local/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#31 /var/www/example.local/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#32 /var/www/example.local/vendor/phing/phing/bin/phing(14): require_once('/var/www/exampl...')
#33 {main}
    [phing] /var/www/example.local/vendor/palantirnet/the-build/tasks/artifact.xml:56:59: Execution of the target buildfile failed. Aborting.
```

**Comment by becw** [comment]
Awesome. On top of that, I tested changing the origin of the build repo, so that it didn't match what was configured in the `build.git.remote` property. When I did that, I got the following error:

```
project > artifact-safeToBuild:

     [echo] Deploy environment:   acquia
     [echo] Repository status:    clean
     [echo] Artifact repository:  artifacts/build has wrong remote configuration
     [echo]   * Directory 'artifacts/build' exists but the 'origin' remote is not artifacts/test-source. Please move or delete before continuing.
     [echo] Destination branch:   artifact-test
     [echo]
[phingcall] /var/www/project.local/vendor/palantirnet/the-build/tasks/artifact.xml:134:12: /var/www/project.local/vendor/palantirnet/the-build/tasks/artifact.xml:138:41: Build state
    [phing] /var/www/project.local/vendor/palantirnet/the-build/tasks/artifact.xml:54:50: Execution of the target buildfile failed. Aborting.
```

This is exactly what is supposed to happen!
